# Generated by Django 3.2.9 on 2021-11-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0012_auto_20211111_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/slider')),
            ],
        ),
    ]
