# Generated by Django 3.2.9 on 2021-11-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0013_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
